name: Staging VM Deployment

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: SSH and run commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.STAGING_VM_HOST }}
        username: ${{ secrets.STAGING_VM_USERNAME }}
        password: ${{ secrets.STAGING_VM_PASSWORD }}
        port: ${{ secrets.STAGING_VM_PORT }}
        script: |
          mkdir hello-world-from-github-pipeline