version: "3.8"
 
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: segment
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - 3307:3306
    volumes:
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql:ro
      - ./mysqlData:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8081:80
