version: "3.8"
 
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DOCKER_MYSQL_DATABASE}
      MYSQL_USER: ${DOCKER_MYSQL_USER}
      MYSQL_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
    ports:
      - ${DOCKER_MYSQL_EXPOSED_PORT}:3306
    volumes:
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql:ro
      - ./mysqlData:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - ${DOCKER_PHPMYADMIN_PORT}:80
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DOCKER_MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DOCKER_MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${DOCKER_MONGO_INITDB_DATABASE}
    ports:
      - ${DOCKER_MONGO_EXPOSED_PORT}:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongoData:/data/db
  mongo-express:
    container_name: mongo-express-backend
    image: mongo-express
    restart: always
    links:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_AUTH_USERNAME: ${DOCKER_MONGO_EXPRESS_ADMIN_AUTH_USERNAME}
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${DOCKER_MONGO_EXPRESS_ADMIN_AUTH_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${DOCKER_MONGO_EXPRESS_BASIC_AUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DOCKER_MONGO_EXPRESS_BASIC_AUTH_PASSWORD}
    ports:
      - ${DOCKER_MONGO_EXPRESS_EXPOSED_PORT}:8081
