package com.zeniapp.segmentmiddleware.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
public enum IntensityTechnique {
    REPEATED_LOW_INTENSITY_EFFORTS("REPEATED_LOW_INTENSITY_EFFORTS"),
    REPEATED_MEDIUM_INTENSITY_EFFORTS("REPEATED_MEDIUM_INTENSITY_EFFORTS"),
    REPEATED_HIGH_INTENSITY_EFFORTS("REPEATED_HIGH_INTENSITY_EFFORTS"),
    REPEATED_MAXIMUM_INTENSITY_EFFORTS("REPEATED_MAXIMUM_INTENSITY_EFFORTS"),
    SUPERSET("SUPERSET"),
    PYRAMID_TRAINING("PYRAMID_TRAINING"),
    INVERTED_PYRAMID_TRAINING("INVERTED_PYRAMID_TRAINING"),
    CLUSTERSET("CLUSTERSET"),
    FORCED_REPS("FORCED_REPS"),
    REST_PAUSE("REST_PAUSE"),
    TRISET("TRISET"),
    NEGATIVE_REPS("NEGATIVE_REPS"),
    PARTIAL_REPS("PARTIAL_REPS"),
    ECCENTRIC_TRAINING("ECCENTRIC_TRAINING"),
    ISOMETRIC_TRAINING("ISOMETRIC_TRAINING"),
    ESCALATING_DENSITY_TRAINING("ESCALATING_DENSITY_TRAINING"),
    GIANTSET("GIANTSET"),
    PRE_EXHAUSTION("PRE_EXHAUSTION"),
    ACCOMMODATING_RESISTANCE("ACCOMMODATING_RESISTANCE"),
    CONTRAST_SET("CONTRAST_SET"),
    TWENTYONE_REPS("TWENTYONE_REPS"),
    DROPSET("DROPSET");

    @Getter
    private String setMethod;
}
